# Generated by Django 5.1 on 2024-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_email_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
    ]
