# Generated by Django 5.1 on 2024-08-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_mobile_number_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_box_1', models.CharField(max_length=100)),
                ('text_box_2', models.CharField(max_length=100)),
                ('dropdown_1', models.CharField(max_length=50)),
                ('dropdown_2', models.CharField(max_length=50)),
            ],
        ),
    ]
