# Generated by Django 5.1 on 2024-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
